# -*- coding: utf-8 -*-
"""Evidencia 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtRh4_L9ftxX8bydB6dY4ClaiTNO0oGs
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/conjunto_de_datos_tmodulo_enape_2021.csv")
df.head()

"""Pregunta PA3.1 ¿(NOMBRE) estuvo inscrita(o) el pasado año o ciclo escolar (2020- 2021)?

Pregunta PA3.2 ¿La escuela donde (NOMBRE) estuvo inscrita(o) (asistió) el pasado ciclo escolar fue...?

Pregunta PA3.4 ¿(NOMBRE) concluyó el grado (semestre, cuatrimestre o módulo) en que estuvo inscrita(o) el pasado año o ciclo escolar (2020-2021)?

Pregunta PA3.5 ¿Cuál fue la razón principal por la que (NOMBRE) no concluyó el grado (semestre, cuatrimestre o módulo)?

Pregunta PB3.1 ¿(NOMBRE) está inscrita(o) en el actual año o ciclo escolar (2021-2022) que inició en agosto/septiembre de 2021?

Pregunta PB3.3 ¿La escuela donde (NOMBRE) está inscrita(o) es...?

Pregunta PB3.4 ¿Cuál fue la razón principal por la que (NOMBRE) se cambió de escuela en el actual año o ciclo escolar (2021-2022)?

Pregunta PB3.5.NIVEL Actualmente, ¿en qué grado (semestre, cuatrimestre o módulo) escolar está inscrita(o) (NOMBRE)? - NIVEL

Pregunta PB3.11.4 ¿Qué medio o medios utiliza(n) la(s) maestra(s) o maestro(s) de (NOMBRE), para informarle sobre las actividades escolares, impartir sus clases o para la entrega de trabajos? - Lo hacen de manera presencial

Pregunta PC3.3.1 ¿(NOMBRE) hasta qué año y grado aprobó en la escuela? - NIVEL

Pregunta PC3.6 ¿Cuál es la razón principal por la que (NOMBRE) dejó de asistir o interrumpió la escuela?
"""

data = df[["SEXO", "PA3_1", "PA3_2", "PA3_4", "PA3_5", "PB3_1", "PB3_3", "PB3_4","PB3_5_NIVEL" ,"PB3_11_4", "PC3_3_1", "PC3_6"]]  # Use a single list for column names

data.head()

data["SEXO"] = data["SEXO"].replace({1: "M", 2: "F"})
data["PA3_1"] = data["PA3_1"].replace({1: "Si", 2: "No"})
data["PA3_2"] = data["PA3_2"].replace({1: "Publica", 2: "Privada"})
data["PA3_4"] = data["PA3_4"].replace({1: "Si", 2: "No"})
data["PA3_5"] = data["PA3_5"].replace({1: "dinero",2: "trabajo", 3: "no interes", 4: "reprobado",5:"cierre escuela", 6:"discapacidad", 7:"pandemia",8:"Covid-19",9:"enfermedad", 10:"matrimonio",11:"hogar", 12: "familia", 13:"problemas personales", 14:"otro"})
data["PB3_1"] = data["PB3_1"].replace({1: "Si", 2: "No"})
data["PB3_3"] = data["PB3_3"].replace({1: "Publica", 2: "Privada"})
data["PB3_4"] = data["PB3_4"].replace({1: "Residencia", 2: "Edad", 3: "Calidad", 4: "universidad",5:"cierre escuela", 6:"costo", 7:"organizacion",8:"motivos personales",9:"gusto", 10:"Covid-19",11:"falta de espacio"})
data["PB3_5_NIVEL"] = data["PB3_5_NIVEL"].replace({1:"Prescolar", 2: "Primaria", 3: "Secundaria", 4: "Profesional tecnico",5:"Preparatoria", 6:"bachillerato tecnologico", 7:"tecnico sup universitario",8:"profesional",9:"especialidad", 10:"maestria",11:"doctorado"})
data["PB3_11_4"] = data["PB3_11_4"].replace({1: "Si", 2: "No se declaro"})
data["PC3_3_1"] = data["PC3_3_1"].replace({0:"Ninguno", 1:"Prescolar", 2: "Primaria", 3: "Secundaria", 4: "Profesional tecnico",5:"Preparatoria", 6:"bachillerato tecnologico", 7:"tecnico sup universitario",8:"profesional",9:"especialidad", 10:"maestria",11:"doctorado"})
data["PC3_6"] = data["PC3_6"].replace({1: "dinero",2: "trabajo", 3: "no interes", 4: "reprobado",5:"falta de escuela", 6:"no requisitos ingreso", 7:"discapacidad",8:"enfermedad",9:"matrimonio",10:"hogar", 11: "familia", 12:"problemas personales", 13:"otro",14:"meta educativa"})
data.head()

# prompt: convertir y descargar la nueva base de datos a un .csv

data.to_csv('new_data.csv', index=False)
from google.colab import files
files.download('new_data.csv')